name: Android Alpha Release

'on':
  workflow_dispatch: null
#- name: Make gradlew executable
#        run: chmod +x ./gradlew
jobs:
  build:
    name: Job 1 - Build Signed AAB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # obtener repo
        with:
          fetch-depth: 0

      - name: Set up JDK 17 # setup java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
     
      
      - name: Setup Gradle Cache # setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10.2"
          gradle-home-cache-cleanup: true
          #cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}

      - name: Configure Keystore # generar el ketsore file y preparar app signing
        run: |
          echo '${{ secrets.STORE_FILE }}'> soundForMeAppKey.jks.asc.b64
          base64 -d -i soundForMeAppKey.jks.asc.b64 > soundForMeAppKey.jks.asc 
          mkdir -p keys
          echo '${{ secrets.KEY_PROPERTIES }}'> key.properties.b64
          base64 -d -i key.properties.b64 > key.properties 
          gpg -d --passphrase '${{ secrets.KEYSTORE_PASSPHRASE }}' --batch soundForMeAppKey.jks.asc > keys/soundForMeAppKey.jks
          echo "storeFile=release.keystore" >> keystore.properties
          echo "keyAlias=$KEY_ALIAS" >> keystore.properties
          echo "storePassword=$STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEY_PASSWORD" >> keystore.properties

      - name: Create Google Play Config file # json con permiso para publicar en play store
        run: |
          mkdir -p app/publish
          echo '${{ secrets.PLAY_CONFIG_JSON }}' > play_config.json.b64
          base64 -d -i play_config.json.b64 > app/publish/pc-api-8834478387068594456-862-5ce7d6e080ae.json 

      - name: Distribute app # publicar app en el open track (seteado en gradle kts)
        run: |
          gradle incrementVersion
          gradle bundleRelease publishBundle