name: Test Version Increment

on:
  workflow_dispatch: # Esto permite disparar el workflow manualmente desde la UI

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh variable list
          gh variable set TEST_VAR --body "Set from workflow"
          gh variable list
        env:
          GH_TOKEN: '${{ secrets.PAT }}'
          VERSION_CODE: '${{ vars.VERSION_CODE}}'
          VERSION_NAME: '${{ vars.VERSION_NAME }}'
