name: Test Version Increment

on:
  workflow_dispatch: # Esto permite disparar el workflow manualmente desde la UI

jobs:
  version-increment:
    name: Increment Version
    runs-on: ubuntu-latest
    steps: 
      - name: Increment VERSION_CODE and VERSION_NAME
        run: |   
          echo "Incremented ASD: $GH_TOKEN"
 
        env:
          GH_TOKEN: ${{ vars.VERSION_CODE }}