name: Test Version Increment

on:
  workflow_dispatch: # Esto permite disparar el workflow manualmente desde la UI

jobs:
  version-increment:
    name: Increment Version
    runs-on: ubuntu-latest
    steps: 
      - name: Increment VERSION_CODE and VERSION_NAME
        run: |   
          echo "Incremented ASD: $((VERSION_CODE))" 

          echo "Incremented VERSION_CODE: $VERSION_CODE"
          echo "Incremented VERSION_NAME: $VERSION_NAME"
          echo "Incremented OLD_MINOR_VERSION: $OLD_MINOR_VERSION"
          gh variable set VERSION_CODE --body "$((VERSION_CODE+1))"

 
        env:
          VERSION_CODE: ${{ vars.VERSION_CODE}}
          VERSION_NAME: ${{ vars.VERSION_NAME }}
          OLD_MINOR_VERSION: $(echo $VERSION_NAME | awk -F'.' '{print $3}')
